### PR TITLE
Add support for pyproject.toml

### PR DESCRIPTION
**Pull request by alexandrebarbaruiva**
Add support for pyproject.toml so that we can add a section as below
```
[tool.ipdb]
context = 10
```

### CODE REVIEW

**Comment by gotcha** [comment]
Great PR with documentation and tests. Thanks

Would you mind adding a changelog entry ?

**Comment by alexandrebarbaruiva** [comment]
Yes, I always seem to forget

**Comment by alexandrebarbaruiva** [comment]
Done!

**Comment by alexandrebarbaruiva** [comment]
@gotcha all done!

**Comment by alexandrebarbaruiva** [comment]
@gotcha is there something else missing?

**Comment by gotcha** [comment]
released in https://pypi.org/project/ipdb/0.13.5/

**Pull request merged**
