### PR TITLE
Add -m option

### PR DESCRIPTION
**Pull request by MrMino**
This adds a `-m` option that was introduced in Python 3.7 pdb. It is
implemented in a backward-compatible way: if the version of python is
lower than 3.7, the script will fallback to shortopts without -m.

See #192.

- Added `-m` option
- Added `test/test_opts.py` for coverage
- Added `mock` to `tests_require` in `setup.py`, so that tests work with Python 2.7.

### CODE REVIEW

**Comment by MrMino** [comment]
@gotcha is there anything I should add here?

**Comment by gotcha** [comment]
@MrMino  No, it is fine as it is. Sorry to have missed it. Do not hesitate to ping me quicker next time.

**Comment by gotcha** [comment]
Released in https://pypi.org/project/ipdb/0.13.4/

**Comment by MrMino** [comment]
Thanks! :)

**Pull request merged**
