### PR TITLE
For python < 3.3, do not install ipython > 6.0.0.

### PR DESCRIPTION
**Pull request by vphilippon**
Beginning with IPython 6.0 (released April 19th 2017), Python 3.3 and above is required.
In order to avoid forcing those installing ipdb with python < 3.3 to add a ipython<6.0 constraints, ipdb can set this limit itself.

I'v noted that there are some exclusion in the test matrix. If the maintainer wants me to add those limits as I just did for python 3.3, I'll gladly add it to this PR.

Cheers!

### CODE REVIEW

**Comment by davidovich** [comment]
This is an excellent example of how extras can be used. But that needs a newer pip to work. Could the minimum pip version be upgraded in the CI ? Pip 6 is almost 3 years old and aggressively wants to upgrade itself.

**Comment by vphilippon** [comment]
By updating the pip and setuptools version in the CI, it works.
But I had to remove python 3.2 as it's not supported by the required pip and setuptools versions.

Ready for review.

**Comment by vphilippon** [comment]
@gotcha I'll take the liberty to poke you, as the value of this change is right now, before everyone using python < 3.3 has to add `ipython < 6.0.0` to their requirements (which is happening right now).

FYI, if this change with the python 3.2 support drop and pip requirements bugs you, I have an alternative quick idea:
Simply change the ipython requirements to  `ipython >= 0.10.2,  < 6.0.0`.
This has the downside of pinning down users with python >= 3.3, but if you prefer that first, and then look into this change and its effects, I'll take it and make another PR super quick.

Thanks for your time!

**Comment by gotcha** [comment]
Thanks ! released as 0.10.3

**Pull request merged**
