### PR TITLE
Add option to use context from env var or config file

### PR DESCRIPTION
**Pull request by alexandrebarbaruiva**
Add option to retrieve context from environment variable `IPDB_CONTEXT_SIZE` or from `setup.cfg` file.

### CODE REVIEW

**Comment by gotcha** [comment]
Thanks for nice PR !
Would you mind adding some documentation and update the changelog ?

**Comment by alexandrebarbaruiva** [comment]
I'll add tests, documentation and update the changelog after the 12th of this month (I'm having tests at my uni :cry: but I'll do it ASAP)!

**Comment by gotcha** [comment]
@alexandrebarbaruiva Take care of your uni tests first ! Good luck

**Comment by alexandrebarbaruiva** [comment]
@gotcha added tests, documentation and updated changelog!

**Comment by gotcha** [comment]
@alexandrebarbaruiva Thanks for your work !

And great for your tests !

FYI, the way you changed HISTORY was breaking the release process with `zest.releaser` (Very convenient tool if you release often to PyPI).
See 8fe1d167cf3f5 where I fixed it.

**Comment by gotcha** [comment]
Released as https://pypi.org/project/ipdb/0.13.1/

**Pull request merged**
