### PR TITLE
Share history across different sessions

### LINKED ISSUE #59: History across different ipdb sessions?
Is it possible to save history across different ipdb sessions? I would like pull up commands from my previous ipdb debug session that was invoked using `ipdb.set_trace()`.

### PR DESCRIPTION
**Pull request by michelesr**
Fix #59

### CODE REVIEW

**Comment by michelesr** [comment]
@gotcha: can you give a feedback on this PR, please?

**Comment by Suor** [comment]
Any updates?

**Comment by darthdeus** [comment]
Anyone working on this? If someone were to resolve the merge conflicts, would this get merged? @gotcha

**Comment by themightyoarfish** [comment]
@gotcha Yes, this seems like an essential usability feature to me.

**Comment by polvoazul** [comment]
Can someone review this?

**Comment by themightyoarfish** [comment]
It's interesting that the repo is still receiving commits, but community contributions get ignore for 3 years (???!!).

**Comment by Suor** [comment]
Yeah, I am waiting for this feature for years.

**Comment by gotcha** [comment]
@michelesr Thanks for your work ! I apologize having left it without feedback for so long.

@darthdeus @polvoazul @themightyoarfish @Suor Thanks for heads up. Please try new PR #190 based on @michelesr work.

**Pull request closed without merging**
